//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Driver_Id { get; set; }
        public string Driver_name { get; set; }
        public string Driver_surname { get; set; }
        public string Driver_email { get; set; }
        public string Driver_password { get; set; }
        public string Driver_phone { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
    }
}
