//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int Id { get; set; }
        public string sender { get; set; }
        public string sender_email { get; set; }
        public string sender_phone { get; set; }
        public string sender_msg { get; set; }
    }
}
