//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string account_no { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string CCV { get; set; }
        public string account_holder { get; set; }
        public Nullable<int> cust_id { get; set; }
    }
}
